In [3]:
import torch

# Gerando dados aleatorios

In [5]:
import random

In [1]:
NUM_NODES = 509
NUM_NODE_FEATURES = 2
NUM_EDGES = 478
NUM_EDGE_FEATURES = 3

In [22]:
NODE_EMBED_SIZE = 4
EDGE_EMBED_SIZE = 6

In [4]:
node_features = torch.rand([509, 2])
edge_features = torch.rand([478, 3])

In [14]:
edge_to_edge_adj_matr = torch.eye(478)
for i in range(len(edge_to_edge_adj_matr)):
    for j in range(len(edge_to_edge_adj_matr[i])):
        if random.random() > 0.5:
            edge_to_edge_adj_matr[i][j] = 1.0
            

In [15]:
node_to_edge_adj_matr = torch.zeros([509, 478])
for i in range(len(node_to_edge_adj_matr)):
    for j in range(len(node_to_edge_adj_matr[i])):
        if random.random() > 0.5:
            node_to_edge_adj_matr[i][j] = 1.0


In [20]:
node_to_node_adj_matr = torch.eye(509)
for i in range(len(node_to_node_adj_matr)):
    for j in range(len(node_to_node_adj_matr[i])):
        if random.random() > 0.5:
            node_to_node_adj_matr[i][j] = 1.0

In [21]:
edge_to_node_adj_matr = torch.zeros([478, 509])
for i in range(len(edge_to_node_adj_matr)):
    for j in range(len(edge_to_node_adj_matr[i])):
        if random.random() > 0.5:
            edge_to_node_adj_matr[i][j] = 1.0

# EdgeLevelAttentionLayer

## Weights

In [23]:
weight_node = torch.rand([NUM_NODE_FEATURES, NODE_EMBED_SIZE])
weight_edge = torch.rand([NUM_EDGE_FEATURES, EDGE_EMBED_SIZE])
parameter_vector_node = torch.rand(NODE_EMBED_SIZE + EDGE_EMBED_SIZE)
parameter_vector_edge = torch.rand(2*EDGE_EMBED_SIZE)

## forward

In [25]:
node_embeds = torch.matmul(node_features, weight_node)

In [27]:
node_embeds.shape

torch.Size([509, 4])

In [28]:
edge_embeds = torch.matmul(edge_features, weight_edge)

In [29]:
edge_embeds.shape

torch.Size([478, 6])

In [35]:
diagonal_n = torch.diag_embed(node_to_edge_adj_matr.T)

In [37]:
diagonal_n.shape

torch.Size([478, 509, 509])

In [38]:
diagonal_e = torch.diag_embed(edge_to_edge_adj_matr.T)

In [40]:
diagonal_e.shape

torch.Size([478, 478, 478])

__Encontrar as features de cada nó vizinho para cada aresta__

In [41]:
features_neighbors_n = torch.matmul(diagonal_n, node_embeds)

In [42]:
features_neighbors_n.shape

torch.Size([478, 509, 4])

In [43]:
features_neighbors_n

tensor([[[0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000],
         ...,
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.1245, 0.0841, 0.1337, 0.1375],
         [0.0000, 0.0000, 0.0000, 0.0000]],

        [[0.2148, 0.1363, 0.1664, 0.2030],
         [1.0572, 0.6094, 0.3763, 0.7637],
         [0.0000, 0.0000, 0.0000, 0.0000],
         ...,
         [0.3850, 0.2442, 0.2980, 0.3637],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.1730, 0.1400, 0.3529, 0.2798]],

        [[0.2148, 0.1363, 0.1664, 0.2030],
         [1.0572, 0.6094, 0.3763, 0.7637],
         [0.0000, 0.0000, 0.0000, 0.0000],
         ...,
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000]],

        ...,

        [[0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000],
         ...,
         [0.0000, 0.0

__Encontrar as features de cada aresta vizinha para cada aresta__

In [44]:
features_neighbors_e = torch.matmul(diagonal_e, edge_embeds)

In [45]:
features_neighbors_e.shape

torch.Size([478, 478, 6])

In [48]:
edge_embeds.repeat_interleave(NUM_NODES, dim=0).reshape(NUM_EDGES, NUM_NODES, EDGE_EMBED_SIZE)

tensor([[[0.9197, 0.4651, 1.4119, 0.6401, 1.1488, 0.5080],
         [0.9197, 0.4651, 1.4119, 0.6401, 1.1488, 0.5080],
         [0.9197, 0.4651, 1.4119, 0.6401, 1.1488, 0.5080],
         ...,
         [0.9197, 0.4651, 1.4119, 0.6401, 1.1488, 0.5080],
         [0.9197, 0.4651, 1.4119, 0.6401, 1.1488, 0.5080],
         [0.9197, 0.4651, 1.4119, 0.6401, 1.1488, 0.5080]],

        [[0.6174, 0.1905, 0.8929, 0.5999, 0.6405, 0.2045],
         [0.6174, 0.1905, 0.8929, 0.5999, 0.6405, 0.2045],
         [0.6174, 0.1905, 0.8929, 0.5999, 0.6405, 0.2045],
         ...,
         [0.6174, 0.1905, 0.8929, 0.5999, 0.6405, 0.2045],
         [0.6174, 0.1905, 0.8929, 0.5999, 0.6405, 0.2045],
         [0.6174, 0.1905, 0.8929, 0.5999, 0.6405, 0.2045]],

        [[1.0228, 0.5490, 1.5935, 0.8002, 1.2957, 0.5456],
         [1.0228, 0.5490, 1.5935, 0.8002, 1.2957, 0.5456],
         [1.0228, 0.5490, 1.5935, 0.8002, 1.2957, 0.5456],
         ...,
         [1.0228, 0.5490, 1.5935, 0.8002, 1.2957, 0.5456],
         [

In [49]:
concat_result_n = torch.cat(
    (
        edge_embeds.repeat_interleave(NUM_NODES, dim=0).reshape([
            NUM_EDGES,
            NUM_NODES,
            EDGE_EMBED_SIZE
        ]),
        features_neighbors_n
    ),
    2
)

In [50]:
concat_result_n

tensor([[[0.9197, 0.4651, 1.4119,  ..., 0.0000, 0.0000, 0.0000],
         [0.9197, 0.4651, 1.4119,  ..., 0.0000, 0.0000, 0.0000],
         [0.9197, 0.4651, 1.4119,  ..., 0.0000, 0.0000, 0.0000],
         ...,
         [0.9197, 0.4651, 1.4119,  ..., 0.0000, 0.0000, 0.0000],
         [0.9197, 0.4651, 1.4119,  ..., 0.0841, 0.1337, 0.1375],
         [0.9197, 0.4651, 1.4119,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.6174, 0.1905, 0.8929,  ..., 0.1363, 0.1664, 0.2030],
         [0.6174, 0.1905, 0.8929,  ..., 0.6094, 0.3763, 0.7637],
         [0.6174, 0.1905, 0.8929,  ..., 0.0000, 0.0000, 0.0000],
         ...,
         [0.6174, 0.1905, 0.8929,  ..., 0.2442, 0.2980, 0.3637],
         [0.6174, 0.1905, 0.8929,  ..., 0.0000, 0.0000, 0.0000],
         [0.6174, 0.1905, 0.8929,  ..., 0.1400, 0.3529, 0.2798]],

        [[1.0228, 0.5490, 1.5935,  ..., 0.1363, 0.1664, 0.2030],
         [1.0228, 0.5490, 1.5935,  ..., 0.6094, 0.3763, 0.7637],
         [1.0228, 0.5490, 1.5935,  ..., 0.0000, 0.0000, 0.

In [51]:
concat_result_n.shape

torch.Size([478, 509, 10])

In [53]:
node_activation = torch.nn.LeakyReLU()

In [54]:
edge_activation = torch.nn.LeakyReLU()

In [58]:
importance_normalization = torch.nn.Softmax(dim=1)

In [68]:
torch.matmul(concat_result_n, parameter_vector_node).shape

torch.Size([478, 509])

In [77]:
importance_coeficients_n = importance_normalization(node_activation(torch.matmul(concat_result_n, parameter_vector_node)))

In [78]:
importance_coeficients_n.shape

torch.Size([478, 509])

In [87]:
torch.matmul(diagonal_n, node_features).shape

torch.Size([478, 509, 2])

In [89]:
importance_coeficients_n

tensor([[0.0006, 0.0006, 0.0006,  ..., 0.0006, 0.0009, 0.0006],
        [0.0010, 0.0043, 0.0006,  ..., 0.0015, 0.0006, 0.0012],
        [0.0010, 0.0044, 0.0006,  ..., 0.0006, 0.0006, 0.0006],
        ...,
        [0.0006, 0.0006, 0.0006,  ..., 0.0006, 0.0009, 0.0012],
        [0.0007, 0.0049, 0.0034,  ..., 0.0007, 0.0010, 0.0007],
        [0.0006, 0.0044, 0.0031,  ..., 0.0016, 0.0006, 0.0012]])

In [88]:
importance_coeficients_n.reshape(478, 509, 1)

tensor([[[0.0006],
         [0.0006],
         [0.0006],
         ...,
         [0.0006],
         [0.0009],
         [0.0006]],

        [[0.0010],
         [0.0043],
         [0.0006],
         ...,
         [0.0015],
         [0.0006],
         [0.0012]],

        [[0.0010],
         [0.0044],
         [0.0006],
         ...,
         [0.0006],
         [0.0006],
         [0.0006]],

        ...,

        [[0.0006],
         [0.0006],
         [0.0006],
         ...,
         [0.0006],
         [0.0009],
         [0.0012]],

        [[0.0007],
         [0.0049],
         [0.0034],
         ...,
         [0.0007],
         [0.0010],
         [0.0007]],

        [[0.0006],
         [0.0044],
         [0.0031],
         ...,
         [0.0016],
         [0.0006],
         [0.0012]]])

In [95]:
torch.matmul(diagonal_n, node_features)

tensor([[[0.0000, 0.0000],
         [0.0000, 0.0000],
         [0.0000, 0.0000],
         ...,
         [0.0000, 0.0000],
         [0.0941, 0.1384],
         [0.0000, 0.0000]],

        [[0.1793, 0.1701],
         [0.9985, 0.3637],
         [0.0000, 0.0000],
         ...,
         [0.3214, 0.3045],
         [0.0000, 0.0000],
         [0.0870, 0.3709]],

        [[0.1793, 0.1701],
         [0.9985, 0.3637],
         [0.0000, 0.0000],
         ...,
         [0.0000, 0.0000],
         [0.0000, 0.0000],
         [0.0000, 0.0000]],

        ...,

        [[0.0000, 0.0000],
         [0.0000, 0.0000],
         [0.0000, 0.0000],
         ...,
         [0.0000, 0.0000],
         [0.0941, 0.1384],
         [0.0870, 0.3709]],

        [[0.0000, 0.0000],
         [0.9985, 0.3637],
         [0.3280, 0.7719],
         ...,
         [0.0000, 0.0000],
         [0.0941, 0.1384],
         [0.0000, 0.0000]],

        [[0.0000, 0.0000],
         [0.9985, 0.3637],
         [0.3280, 0.7719],
         ...,
 

In [97]:
(importance_coeficients_n.reshape(NUM_EDGES, NUM_NODES, 1)* torch.matmul(diagonal_n, node_features)).shape

torch.Size([478, 509, 2])

In [102]:
means_n = torch.mean(importance_coeficients_n.reshape(NUM_EDGES, NUM_NODES, 1)* torch.matmul(diagonal_n, node_features), 1)

In [104]:
output_nodes = node_activation(
    torch.matmul(
        means_n,
        weight_node
    )
)

In [105]:
output_nodes.shape

torch.Size([478, 4])

In [106]:
output_nodes

tensor([[0.0013, 0.0008, 0.0010, 0.0012],
        [0.0013, 0.0008, 0.0010, 0.0012],
        [0.0013, 0.0008, 0.0010, 0.0012],
        ...,
        [0.0013, 0.0008, 0.0010, 0.0012],
        [0.0012, 0.0008, 0.0009, 0.0011],
        [0.0012, 0.0008, 0.0010, 0.0012]])

## Calculado para as arestas vizinhas

In [107]:
concat_result_e = torch.cat(
    (
        edge_embeds.repeat_interleave(NUM_EDGES, dim=0).reshape([
            NUM_EDGES,
            NUM_EDGES,
            EDGE_EMBED_SIZE
        ]),
        features_neighbors_e
    ),
    2
)

In [109]:
concat_result_e.shape

torch.Size([478, 478, 12])

In [110]:
attention_output_e = edge_activation(torch.matmul(concat_result_e, parameter_vector_edge))

In [111]:
importance_coeficients_e = importance_normalization(attention_output_e)

In [113]:
means_e = torch.mean(importance_coeficients_e.reshape(NUM_EDGES, NUM_EDGES, 1)* torch.matmul(diagonal_e, edge_features), 1)

In [114]:
means_e.shape

torch.Size([478, 3])

In [115]:
output_edges = edge_activation(
    torch.matmul(
        means_e,
        weight_edge
    )
)

In [119]:
output_edges.shape

torch.Size([478, 6])

In [118]:
torch.cat((output_nodes, output_edges), dim=1).shape

torch.Size([478, 10])